Seccion47Admin/Seccion.Web/Controllers/UploadLayoutController.cs
using AutoMapper;
using OfficeOpenXml;
using Seccion.Model.Enums;
using Seccion.Model.Models;
using Seccion.Service.Common.Message;
using Seccion.Service.ServiceInterface;
using Seccion.Web.Common;
using Seccion.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Validation;
using System.Data.SqlTypes;
using System.Globalization;
using System.Linq;
using System.Security.Permissions;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Seccion.Web.Controllers
{
    public class UploadLayoutController : Controller
    {
        public readonly INotifier _INotifier;
        public readonly IStatesService _IStatesService;
        public readonly IMunicipalitiesService _IMunicipalitiesService;
        public readonly IEmployeeService _IEmployeeService;
        public readonly ITbBoxesService _ITbBoxesService;

        public UploadLayoutController(INotifier iNotifier, IStatesService iStatesService, IMunicipalitiesService iMunicipalitiesService, IEmployeeService iEmployeeService, ITbBoxesService ITbBoxesService)
        {
            _INotifier = iNotifier;
            _IStatesService = iStatesService;
            _IMunicipalitiesService = iMunicipalitiesService;
            _IEmployeeService = iEmployeeService;
            _ITbBoxesService = ITbBoxesService;
        }

        // GET: UploadLayout
        public ActionResult UplaoadMembers()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> UplaoadMembers(HttpPostedFileBase file)
        {
            try
            {
                var lstStates = await _IStatesService.GetAll();
                var lstMunicipalities = await _IMunicipalitiesService.GetAll();

                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                using (ExcelPackage package = new ExcelPackage(file.InputStream))
                {
                    var lstEmployee = new List<TbEmployee>();
                    var CurrentSheet = package.Workbook.Worksheets;
                    var WorkSheet = CurrentSheet.First();
                    var TotalRow = WorkSheet.Dimension.End.Row;

                    for (int iRow = 4; iRow <= TotalRow; iRow++)
                    {
                        var employeeViewModel = new EmployeeVIewModel();

                        if (WorkSheet.Cells[iRow, 2].Value != null)
                        {
                            employeeViewModel.NumberFicha = WorkSheet.Cells[iRow, 2].Text;
                        }
                        else
                        {
                            _INotifier.AddMessage(MessageSeverity.Info, $"Fila: {iRow}, Columna: {WorkSheet.Cells[iRow, 2].Address}", "Este campo es requerido");
                        }
                        if (WorkSheet.Cells[iRow, 3].Value != null)
                        {
                            employeeViewModel.Name = WorkSheet.Cells[iRow, 3].Text;
                        }
                        else
                        {
                            _INotifier.AddMessage(MessageSeverity.Info, $"Fila: {iRow}, Columna: {WorkSheet.Cells[iRow, 3].Address}", "Este campo es requerido");
                        }
                        if (WorkSheet.Cells[iRow, 4].Value != null)
                        {
                            employeeViewModel.FirstName = WorkSheet.Cells[iRow, 4].Text;
                        }
                        else
                        {
                            _INotifier.AddMessage(MessageSeverity.Info, $"Fila: {iRow}, Columna: {WorkSheet.Cells[iRow, 4].Address}", "Este campo es requerido");
                        }
                        if (WorkSheet.Cells[iRow, 5].Value != null)
                        {
                            employeeViewModel.LastName = WorkSheet.Cells[iRow, 5].Text;
                        }
                        else
                        {
                            _INotifier.AddMessage(MessageSeverity.Info, $"Fila: {iRow}, Columna: {WorkSheet.Cells[iRow, 5].Address}", "Este campo es requerido");
                        }
                        employeeViewModel.RFC = WorkSheet.Cells[iRow, 6].Value != null ? WorkSheet.Cells[iRow, 6].Text : null;
                        employeeViewModel.CURP = WorkSheet.Cells[iRow, 7].Value != null ? WorkSheet.Cells[iRow, 7].Text : null;
                        employeeViewModel.INE = WorkSheet.Cells[iRow, 8].Value != null ? WorkSheet.Cells[iRow, 8].Text : null;
                        if (WorkSheet.Cells[iRow, 9].Value != null)
                        {
                            var value = WorkSheet.Cells[iRow, 9].Text;
                            if (Enum.IsDefined(typeof(EmployeeRol), value))
                            {
                                employeeViewModel.Rol = value;
                            }
                            else
                            {
                                _INotifier.AddMessage(MessageSeverity.Info, $"Fila: {iRow}, Columna: {WorkSheet.Cells[iRow, 9].Address}", "El Rol no se encuentra registrado, favor de validar");
                            }
                        }
                        else
                        {
                            employeeViewModel.Rol = null;
                        }

                        if (WorkSheet.Cells[iRow, 10].Value != null)
                        {
                            var value = WorkSheet.Cells[iRow, 10].Text;
                            if (Enum.IsDefined(typeof(Region), value))
                            {
                                employeeViewModel.Region = value;
                            }
                            else
                            {
                                _INotifier.AddMessage(MessageSeverity.Info, $"Fila: {iRow}, Columna: {WorkSheet.Cells[iRow, 10].Address}", "La Region no se encuentra registrada, favor de validar");
                            }
                        }
                        else
                        {
                            employeeViewModel.Region = null;
                        }

                        if (WorkSheet.Cells[iRow, 11].Value != null)
                        {
                            var value = WorkSheet.Cells[iRow, 11].Text;
                            if (Enum.IsDefined(typeof(ContractualSituation), value))
                            {
                                employeeViewModel.ContractualSituation = value;
                            }
                            else
                            {
                                _INotifier.AddMessage(MessageSeverity.Info, $"Fila: {iRow}, Columna: {WorkSheet.Cells[iRow, 11].Address}", "La Situacion Contractual no se encuentra registrada, favor de validar");
                            }
                        }
                        else
                        {
                            employeeViewModel.ContractualSituation = null;
                        }

                        if (WorkSheet.Cells[iRow, 12].Value != null)
                        {
                            var value = WorkSheet.Cells[iRow, 12].Text;
                            if (Enum.IsDefined(typeof(WorkLocation), value))
                            {
                                employeeViewModel.WorkLocation = value;
                            }
                            else
                            {
                                _INotifier.AddMessage(MessageSeverity.Info, $"Fila: {iRow}, Columna: {WorkSheet.Cells[iRow, 12].Address}", "La Ubicacion Laboral no se encuentra registrada, favor de validar");
                            }
                        }
                        else
                        {
                            employeeViewModel.WorkLocation = null;
                        }
                        employeeViewModel.DepartmentKey = WorkSheet.Cells[iRow, 13].Value != null ? WorkSheet.Cells[iRow, 13].Text : null;
                        employeeViewModel.AsisteKey = WorkSheet.Cells[iRow, 14].Value != null ? WorkSheet.Cells[iRow, 14].Text : null;

                        if (WorkSheet.Cells[iRow, 15].Value != null)
                        {
                            employeeViewModel.Level = Convert.ToInt32(WorkSheet.Cells[iRow, 15].Text);
                        }
                        else
                        {
                            _INotifier.AddMessage(MessageSeverity.Info, $"Fila: {iRow}, Columna: {WorkSheet.Cells[iRow, 15].Address}", "Este campo es requerido");
                        }

                        if (WorkSheet.Cells[iRow, 16].Value != null)
                        {
                            employeeViewModel.Address = WorkSheet.Cells[iRow, 16].Text;
                        }
                        else
                        {
                            _INotifier.AddMessage(MessageSeverity.Info, $"Fila: {iRow}, Columna: {WorkSheet.Cells[iRow, 16].Address}", "Este campo es requerido");
                        }

                        if (WorkSheet.Cells[iRow, 17].Value != null)
                        {

                            var NameState = WorkSheet.Cells[iRow, 17].Text;
                            var objStates = lstStates.FirstOrDefault(x => x.NameSate == NameState);
                            if (objStates != null)
                            {
                                employeeViewModel.TbStatesId = objStates.TbStatesId;

                                if (WorkSheet.Cells[iRow, 18].Value != null)
                                {
                                    var NameMunicipalities = WorkSheet.Cells[iRow, 18].Text;
                                    var objMunicipalities = lstMunicipalities.FirstOrDefault(x => x.TbStatesId == objStates.TbStatesId && x.NameMunicipalities == NameMunicipalities);

Seccion47Admin/Seccion.Web/Views/UploadLayout/UplaoadMembers.cshtml
@{
    ViewBag.Title = "UplaoadMembers";
}

@using (Html.BeginForm("UplaoadMembers", "UploadLayout", FormMethod.Post, new { enctype = "multipart/form-data", id = "myform" }))
{
    @Html.Partial("_UploadFile")
}
@section PageCrumb{
    <small class="page-info text-secondary-d2">
        <i class="fa fa-angle-double-right text-80" aria-hidden="true"></i>
        Carga de Agremiados
    </small>
}

Seccion47Admin/Seccion.Web/Views/UploadLayout/UploadInformationBoxes.cshtml
@{
	ViewBag.Title = "UploadInformationBoxes";
}

@using (Html.BeginForm("UploadInformationBoxes", "UploadLayout", FormMethod.Post, new { enctype = "multipart/form-data", id = "myform" }))
{
	@Html.Hidden("OldBox", false)
	@Html.Hidden("CashBox", false)
	@Html.Hidden("NewBox", false)

	<div class="h-100 bg-white pt-0 radius-1 shadow-lg mx-auto">
		<div class="border-t-3 w-100 brc-dark radius-t-1"></div>
		<div class="card border-0 h-100">
			<div class="card-header brc-dark-l2">
				<h5 class="card-title text-110 text-dark font-bold pt-1 text-uppercase">
					<i class="fa fa-table mr-2px" aria-hidden="true"></i>
					Carga Informacion de Cajas: Seleccione el tipo de Archivo
				</h5>
			</div>
			<div class="card-body bg-white p-4 collapse show">
				<div class="row">
					<div class="col-md-2">
						<div>
							<label class="text-600 text-uppercase text-95 text-secondary">
								<input type="radio" id="chkOldBox" name="box" class="input-lg text-danger-m1 brc-on-checked brc-success brc-h-success-m1 border-2" />
								Caja Vieja
							</label>
						</div>
					</div>
					<div class="col-md-3">
						<div>
							<label class="text-600 text-uppercase text-95 text-secondary">
								<input type="radio" id="chkCashBox" name="box" class="input-lg text-danger-m1 brc-on-checked brc-success brc-h-success-m1 border-2" />
								Caja de Tesoreria
							</label>
						</div>
					</div>
					<div class="col-md-2">
						<div>
							<label class="text-600 text-uppercase text-95 text-secondary">
								<input type="radio" id="chkNewBox" name="box" class="input-lg text-danger-m1 brc-on-checked brc-success brc-h-success-m1 border-2" />
								Caja Nueva
							</label>
						</div>
					</div>
				</div>
				<br />
				@Html.Partial("_UploadFile")
			</div>
		</div>
	</div>
}
@section PageCrumb{
	<small class="page-info text-secondary-d2">
		<i class="fa fa-angle-double-right text-80" aria-hidden="true"></i>
		Carga Informacion de Cajas
	</small>
}
<script @Html.CspScriptNonce()>
	$(document).ready(function () {
		$("input[name=box]").on("click", function () {
			$("#OldBox").val($("#chkOldBox").is(":checked"));
			$("#CashBox").val($("#chkCashBox").is(":checked"));
			$("#NewBox").val($("#chkNewBox").is(":checked"));
		});
	});
</script>

Seccion47Admin/Seccion.Web/Views/UploadLayout/_UploadFile.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="h-100 bg-white pt-0 radius-1 shadow-lg mx-auto">
            <div class="border-t-3 w-100 brc-dark radius-t-1"></div>
            <div class="card border-0 h-100">
                <div class="card-header brc-dark-l2">
                    <h5 class="card-title text-110 text-dark font-bold pt-1 text-uppercase">
                        <i class="fa fa-table mr-2px" aria-hidden="true"></i>
                        Carga de Archivo
                    </h5>
                </div>
                <div class="card-body bg-white p-0 collapse show">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="file-loading">
                                <input type="file" id="file" name="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<link href="~/assetsAce/bootstrap-fileinput/css/fileinput.css" rel="stylesheet" />
<script src="~/assetsAce/bootstrap-fileinput/Scripts/fileinput.js"></script>
<script src="~/assetsAce/bootstrap-fileinput/themes/fas/theme.js"></script>
<script src="~/assetsAce/bootstrap-fileinput/Scripts/locales/es.js"></script>
<script @Html.CspScriptNonce()>
    $(document).ready(function () {
        $("#file").fileinput({
            language: 'es',
            theme: 'fas',
            showBrowse: false,
            allowedPreviewTypes: null,
            browseOnZoneClick: true,
            uploadAsync: false,
            overwriteInitial: false,
            previewFileExtSettings: {
                'xls': function (ext) {
                    return ext.match(/(xls|xlsx)$/i);
                }
            },
        });

    });

</script>