Seccion47Admin/Seccion.Web/Controllers/CommonController.cs
using Seccion.Data.RepositoriesSP;
using Seccion.Service.ServiceInterface;
using Seccion.Web.Models.GridListModel;
using Seccion.Web.Models.ViewModels;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Seccion.Web.Controllers
{
    public class CommonController : Controller
    {
        private readonly IEmployeeService employeeService;
        private readonly IAccountUserService _IAccountUserService;
        private readonly IMenuService _IMenuService;

        public CommonController(IEmployeeService employeeService, IAccountUserService IAccountUserService, IMenuService IMenuService, ISP_GetMenuRepository ISP_GetMenuRepository)
        {
            this.employeeService = employeeService;
            _IAccountUserService = IAccountUserService;
            _IMenuService = IMenuService;
        }
        // GET: Common
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult DataTableMenu(MenuIdModel model)
        {
            return PartialView("_TableMenu", model);
        }
        [HttpGet]
        public async Task<JsonResult> GetEmployeeAval()
        {
            var listEmployee = await employeeService.GetEmployeeData();
            return Json(listEmployee, JsonRequestBehavior.AllowGet);
        }


        public ActionResult RenderMenu()
        {
            return PartialView("_LayoutMenu", Session["Menu"] as MenuViewModel);
        }

    }
}

Seccion47Admin/Seccion.Web/Views/Shared/_FooterPage.cshtml
<footer class="footer d-none d-sm-block">
	<div class="footer-inner">
		<div class="h-100 pt-3 border-none border-t-1 brc-default-l1 bgc-white-tp1 shadow">
			<span class="text-dark font-bolder text-120">SECCIÓN 47</span>
			<span class="text-muted">Administración © @DateTime.Now.Year</span>
		</div>
	</div><!-- .footer-inner -->
</footer>

<div class="footer-tools">
	<a id="btn-scroll-up" href="#" class="btn-scroll-up btn btn-white brc-black-tp7 btn-smd border-2 radius-round mb-2 mr-2">
		<i class="fa fa-angle-double-up w-2 h-2" aria-hidden="true"></i>
	</a>
</div>

Seccion47Admin/Seccion.Web/Views/Shared/_LayoutLogin.cshtml
@using Seccion.Service.Common.Message;
@using NWebsec.Mvc.HttpHeaders.Csp
<!DOCTYPE html>

<html lang="es-mx">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
	<title>@ViewBag.Title</title>

	@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@
	@*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
		<link href="~/assetsAce/node_modules/fortawesome/fontawesome-free/css/fontawesome.css" rel="stylesheet" />
		<link href="~/assetsAce/node_modules/fortawesome/fontawesome-free/css/solid.css" rel="stylesheet" />
		<link href="~/assetsAce/node_modules/dist/css/ace.min.css" rel="stylesheet" />
		<link href="~/assetsAce/css/login/page-login-style.css" rel="stylesheet" />*@
	@Styles.Render("~/Ace/loginLayoutCss")
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons" />
	<link rel="icon" type="image/png" href="~/assetsAce/image/favicon.ico" />


</head>
<body>
	<div class="body-container">
		<div class="main-container container">

			<div role="main" class="main-content minh-100 justify-content-center">
				<div class="p-2 p-md-4 h-100">
					<div class="row h-100">
						<div class="shadow radius-1 overflow-hidden bg-white col-12 col-lg-10 offset-lg-1">

							<div class="row h-100">

								<div class="d-none d-lg-flex col-lg-5 border-r-1 brc-default-l2 px-0">
									<div id="loginBgCarousel" class="carousel slide minw-100 h-100">
										<ol class="carousel-indicators d-none">
											<li data-target="#loginBgCarousel" data-slide-to="0" class="active"></li>
										</ol>

										<div class="carousel-inner minw-100 h-100">

											<div class="carousel-item active minw-100 h-100">
												<div style="background-image: url(../../assetsAce/image/login-bg-3.jpg);" class="d-flex flex-column align-items-center justify-content-start">
													<div class="bgc-black-tp4 radius-1 p-3 w-90 text-center my-3 h-100">
														<h1><i class="fa fa-leaf text-success-m2 text-125" aria-hidden="true"></i></h1>
														<h2 class="text-blue-l1">
															Seccion 47 <span class="text-80 text-white-tp3">  MUT47</span>
														</h2>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="col-lg-7 py-lg-5 bgc-white px-0">
									@Html.ViewContext.DisplayMessages()
									@RenderBody()
								</div>



							</div>

						</div>
					</div>

					<div class="d-lg-none my-3 text-white-tp1 text-center text-uppercase">
						<i class="fa fa-leaf text-success-l3 mr-1 text-110 " aria-hidden="true"></i> Sección 47 Company &copy; @DateTime.Now.Year
					</div>
				</div>
			</div>

		</div>

	</div>


	@Scripts.Render("~/bundles/loginLayoutJs")
	@RenderSection("scripts", required: false)

	@Scripts.Render("~/bundles/jqueryval")
	<script src="~/Scripts/Forms/VariblesJSONToValidation.js"></script>
	<script src="~/Scripts/Forms/RudolfUtilities.js"></script>

</body>
</html>

Seccion47Admin/Seccion.Web/Views/Shared/_LayoutMaster.cshtml
@using Seccion.Service.Common.Message;
<!DOCTYPE html>

<html lang="es-mx">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
	<base href="../" />

	<title>Seccion</title>

	<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
	<link href="~/assetsAce/node_modules/fortawesome/fontawesome-free/css/fontawesome.css" rel="stylesheet" />
	<link href="~/assetsAce/node_modules/fortawesome/fontawesome-free/css/solid.css" rel="stylesheet" />

	@if (IsSectionDefined("styles"))
	{
		@RenderSection("styles")
	}

	<link href="~/assetsAce/node_modules/dist/css/ace.min.css" rel="stylesheet" />
	<link href="~/assetsAce/node_modules/dist/css/ace-themes.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons" />
	<link href="~/assetsAce/css/Style.css" rel="stylesheet" />
	<link rel="icon" type="image/png" href="~/assetsAce/image/favicon.ico" />

	<script src="~/Scripts/jquery-3.4.1.min.js"></script>

</head>

<body>
	<div class="body-container">
		<div class="main-container">

			<div id="sidebar" class="sidebar sidebar-fixed sidebar-backdrop expandable sidebar-color sidebar-gradient2" data-swipe="true" data-dismiss="true">
				<div class="sidebar-inner">

					<!-- .navbar-brand inside sidebar, only show in desktop view -->
					<div class="d-none d-xl-flex sidebar-section-item m-0 fadeable-left fadeable-top">
						<div class="fadeinable">
							<div class="py-2 mx-1 border-b-1 brc-white-tp9" id="sidebar-header-brand1">
								<a class="navbar-brand text-white-tp1 text-140">
									<i class="fa fa-leaf text-success-l3" aria-hidden="true"></i>
								</a>
							</div>
						</div>

						<div class="fadeable w-100 ">
							<div class="py-2 text-center mx-3 border-b-1 brc-white-tp9" id="sidebar-header-brand2">

								<a class="navbar-brand ml-n2 text-white-tp1 text-140" href="#">
									<i class="fa fa-industry mr-1 text-success-l3" aria-hidden="true"></i>
									SECCIÓN <span>47</span>
								</a>

							</div>
						</div>
					</div><!-- /.sidebar-section-item  -->


					<div class="pt-2 flex-grow-1 ace-scroll" ace-scroll="">
						@{
							Html.RenderPartial("_MyPrincipalProfile");
						}

						<ul class="nav flex-column mt-2 has-active-border active-on-top has-active-arrow" role="navigation" aria-label="Main">
							<li class="nav-item-caption">
								<span class="fadeable pl-3 text-uppercase">Menú de Navegación</span>
								<span class="fadeinable mt-n2 text-125">…</span>
							</li>
							@{Html.RenderAction("RenderMenu", "Common"); }
						</ul>

					</div>
				</div>
			</div>

			<div role="main" class="main-content">
				<nav class="navbar navbar-sm navbar-expand-lg navbar-fixed navbar-mediumseagreen">
					<div class="navbar-inner">

						<div class="justify-content-xl-between d-flex h-100 align-items-center">

							<button type="button" class="btn burger-arrowed static collapsed ml-2 d-flex d-xl-none btn-burger" data-toggle-mobile="sidebar" data-target="#sidebar" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle sidebar">
								<span class="bars"></span>
							</button>

							<a class="navbar-brand d-xl-none text-white" href="#">
								<i class="fa fa-industry" aria-hidden="true"></i>
								SECCIÓN
								<span class="d-sm-inline-block">47</span>
							</a>

							<button type="button" class="btn align-self-center mx-2 d-none d-xl-flex btn-burger" data-toggle="sidebar" data-target="#sidebar" aria-controls="sidebar" aria-expanded="true" aria-label="Toggle sidebar">
								<span class="bars"></span>
							</button>
						</div>


						<div class="navbar-content">


						</div><!-- .navbar-content -->
						<!-- .navbar-menu togger -->
						<button class="navbar-toggler ml-1 mr-2 px-1" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navbar menu">
							<img class="" src="~/assetsAce/image/avatar/logo.png" width="50" height="64" alt="Jason's Photo">
						</button>


						<div class="navbar-menu collapse navbar-collapse navbar-backdrop" id="navbarMenu">
							<div class="navbar-nav">

								@{
									Html.RenderPartial("_MyProfile");
								}

								<!-- /.navbar-nav menu -->
							</div>


						</div>


					</div>
				</nav>
				<div class="page-content container">
					<div id="stack-context" class="page-header">
						<h4 class="page-title text-primary-d2">
							<a href="@Url.Action("Index","Home")">Home</a>

							@if (IsSectionDefined("PageCrumb"))
							{
								@RenderSection("PageCrumb")
							}
						</h4>
					</div>
					@Html.ViewContext.DisplayMessages()
					@RenderBody()
					@if (IsSectionDefined("scripts"))
					{
						@RenderSection("scripts")
					}

				</div><!-- /.page-content -->

				@{
					Html.RenderPartial("_FooterPage");
				}
			</div><!-- /main -->

		</div><!-- /.main-container -->

	</div><!-- /.body-container -->
	<!-- include common vendor scripts used in demo pages -->
	@*<script src="~/assetsAce/js/layoutpage/loadpage.js"></script>*@
	<script src="~/assetsAce/node_modules/js/plugins/popperjs/popper.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>
	<script src="~/assetsAce/node_modules/dist/js/ace.min.js"></script>
	<script src="~/assetsAce/node_modules/js/plugins/notify/PNotify.js"></script>
	<script src="~/assetsAce/node_modules/js/plugins/notify/PNotifyStyleMaterial.js"></script>
	<script src="~/assetsAce/node_modules/js/plugins/notify/PNotifyButtons.js"></script>
	<script src="~/assetsAce/node_modules/js/plugins/notify/PNotifyAnimate.js"></script>

	@*<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
		<script src="~/assetsAce/node_modules/js/plugins/loadingoverlay/loadingoverlay.min.js"></script>*@

	<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
	<script src="~/assetsAce/node_modules/js/plugins/loadingoverlay/loadingoverlay.min.js"></script>


	@Scripts.Render("~/bundles/jqueryval")
	<script src="~/Scripts/Forms/RudolfUtilities.js"></script>
	<script src="~/assetsAce/js/layoutpage/loadpage.js"></script>
</body>
</html>

Seccion47Admin/Seccion.Web/Views/Shared/_LayoutMenu.cshtml
@model Seccion.Web.Models.ViewModels.MenuViewModel
@using Seccion.Web.Common.Menu

@Html.CreateMenu(Model.MenuItems)

Seccion47Admin/Seccion.Web/Views/Shared/_MyPrincipalProfile.cshtml
<div class="sidebar-section-item mx-0  fadeable-left fadeable-top">
	<div class="fadeinable">
		<img src="~/assetsAce/image/avatar/logo.png" width="80" height="100" class="" alt="">
	</div>

	<div class="fadeable hideable">

		<div class="py-2 d-flex flex-column align-items-center">
			<div>
				<img src="~/assetsAce/image/avatar/logo.png" width="80" height="100" class="" alt="">
			</div>

			<div class="text-center mt-1" id="id-user-info">
				<a href="#id-user-menu" class="d-style pos-rel collapsed accordion-toggle no-underline px-1 py-2px text-white-tp1 text-center" data-toggle="collapse" aria-expanded="false">
					<span class="text-95 font-bolder">@User.Identity.GetName()</span>
					<i class="fa fa-caret-down text-90 d-collapsed" aria-hidden="true"></i>
					<i class="fa fa-caret-up text-90 d-n-collapsed" aria-hidden="true"></i>
				</a>
				<div class="text-white-tp2 text-80">Marketing</div>
			</div><!-- /#id-user-info -->

			<div class="collapse" id="id-user-menu">
				<div class="mt-3">
					<a href="@Url.Action("MyUserData", "AccountUser")" class="btn bgc-blue-l2 btn-brc-white btn-h-outline-blue radius-round py-2 px-1 text-center border-2 shadow-sm">
						<i class="fa fa-id-card w-4 text-110 text-blue-m1" aria-hidden="true"></i>
					</a>

					<a href="@Url.Action("ChangePassword","AccountUser")" class="btn bgc-purple-l2 btn-brc-white btn-h-outline-purple radius-round py-2 px-1 text-center border-2 shadow-sm">
						<i class="fa fa-user-secret w-4 text-110 text-purple-m1" aria-hidden="true"></i>
					</a>
				</div>
			</div><!-- /.collapse -->

		</div>

	</div>
</div>

Seccion47Admin/Seccion.Web/Views/Shared/_MyProfile.cshtml
@using Microsoft.AspNet.Identity;
<ul class="nav">

    <li class="nav-item dropdown dropdown-mega">
        <a class="nav-link dropdown-toggle pl-lg-3 pr-lg-4" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-bell text-110 icon-animated-bell mr-lg-2" aria-hidden="true"></i>

            <span class="d-inline-block d-lg-none ml-2">Notificaciones</span><!-- show only on mobile -->
            <span id="id-navbar-badge1" class="badge badge-sm badge-warning radius-round text-80 border-1 brc-white-tp5">0</span>

            <i class="caret fa fa-angle-left d-block d-lg-none" aria-hidden="true"></i>
            <div class="dropdown-caret brc-white"></div>
        </a>
        <div class="shadow dropdown-menu dropdown-animated dropdown-sm p-0 bg-white brc-primary-m3 border-1 border-b-2">
            <ul class="nav nav-tabs nav-tabs-simple w-100 nav-justified dropdown-clickable border-b-1 brc-default-m4">
                <li class="nav-item">
                    <a class="d-style px-0 mx-0 py-3 nav-link active text-600 brc-blue-m2 text-grey-m3 bgc-h-blue-l4" data-toggle="tab" href="#navbar-notif-tab-1" role="tab">
                        <span class="d-active text-blue-m1 text-105">Notificaciones</span>
                        <span class="d-n-active">Notificaciones</span>
                    </a>
                </li>
            </ul><!-- .nav-tabs -->


            <div class="tab-content tab-sliding p-0">

                <div class="tab-pane mh-none show active px-md-1 pt-1" id="navbar-notif-tab-1" role="tabpanel">
                    <div id="navbar-notif-tab-1-child">

                    </div>

                    <hr class="mt-1 mb-1px brc-info-m4" />
                    <a href="@Url.Action("Index", "Card")" class="mb-0 py-3 border-0 list-group-item text-blue-m2 text-uppercase text-center text-85 font-bold">
                        Ver todas las notificaciones
                        <i class="ml-2 fa fa-arrow-right text-muted" aria-hidden="true"></i>
                    </a>
                </div><!-- .tab-pane : notifications -->
            </div>
        </div>
    </li>

    <li class="nav-item dropdown order-first order-lg-last">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <div class="pl-1">
                <span class="d-inline-block bgc-danger p-2 radius-round text-center w-6 h-6 mr-3">
                    <i class="fa fa-user text-white text-180 d-inline-block " aria-hidden="true"></i>
                </span>
            </div>
            <span class="d-inline-block d-lg-none d-xl-inline-block">
                <span class="text-90" id="id-user-welcome">Bienvenido,</span>
                <span class="nav-user-name">@User.Identity.GetName()</span>
            </span>

            <i class="caret fa fa-angle-down d-none d-xl-block" aria-hidden="true"></i>
            <i class="caret fa fa-angle-left d-block d-lg-none" aria-hidden="true"></i>
        </a>

        <div class="dropdown-menu dropdown-caret dropdown-menu-right dropdown-animated brc-primary-m3">
            <div class="d-none d-lg-block d-xl-none">
                <div class="dropdown-header">
                    Welcome, @User.Identity.GetName()
                </div>
                <div class="dropdown-divider"></div>
            </div>

            <a class="dropdown-item btn btn-outline-grey btn-h-lighter-success btn-a-lighter-success" href="@Url.Action("EditMyData", "AccountUser")/@User.Identity.GetUserId()">
                <i class="fa fa-user-edit text-dark text-110 mr-1" aria-hidden="true"></i>
                Editar Mis Datos
            </a>

            <a class="dropdown-item btn btn-outline-grey btn-h-lighter-success btn-a-lighter-success" href="@Url.Action("ChangePassword", "AccountUser")">
                <i class="fa fa-user-secret text-dark text-110 mr-1" aria-hidden="true"></i>
                Cambiar Contraseña
            </a>

            <div class="dropdown-divider brc-primary-l2"></div>

            <a class="dropdown-item btn btn-outline-grey btn-h-lighter-success btn-a-lighter-success" href="@Url.Action("LogOff", "Login")">
                <i class="fa fa-power-off text-danger text-110 mr-1" aria-hidden="true"></i>
                Cerrar Sesión
            </a>
        </div>
    </li><!-- /.nav-item:last -->
</ul>

<style>
    .fade:not(.show) {
        opacity: 1 !important;
    }

    [ui-pnotify].ui-pnotify.stack-bar-top {
        width: 75%;
    }
</style>
@*
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons" />*@
<link href="~/assetsAce/node_modules/js/plugins/notify/animate.min.css" rel="stylesheet" />
<script type="text/javascript">
    $(function () {

        //NotifierMessage(messageSeverity.Info, "¡Información!", "Tienes una nueva notificacion del usuario");

        $.ajax({
            "async": true,
            "crossDomain": true,
            "url": "/Home/GetNotifications/",
            "cache": false,
            "method": "GET",
            //"contentType": 'application/json; charset=utf-8',
        }).done(function (data) {
            document.getElementById("id-navbar-badge1").innerHTML = data.newNotification;

            data.data.forEach(function (valor, indice, array) {
                var elementA = document.createElement("a");
                elementA.className = "mb-0 border-0 list-group-item list-group-item-action btn-h-lighter-secondary";
                elementA.href = "Card/EditCard?id=" + valor.TbNotificationId;

                var elementI = document.createElement("i");
                elementI.className = "fa fa-comment bgc-pink-tp1 text-white text-110 mr-1 p-2 radius-1";
                elementA.appendChild(elementI);

                var elementSpan1 = document.createElement("span");
                elementSpan1.className = "text-muted";
                elementSpan1.innerText = valor.Title;
                elementA.appendChild(elementSpan1);

                var elementSpan2 = document.createElement("span");
                elementSpan2.className = "float-right badge badge-info radius-round text-80";
                elementSpan2.innerText = valor.UserInsert;
                elementA.appendChild(elementSpan2);

                document.getElementById("navbar-notif-tab-1-child").appendChild(elementA);
            });

        }).fail(function (jqXHR, textStatus, err) {
            //MessageError(jqXHR, textStatus, err, Title, "LnkMessage");
        });
    });
</script>

Seccion47Admin/Seccion.Web/Views/Shared/_TableMenu.cshtml
@model Seccion.Web.Models.GridListModel.MenuIdModel

<div class='dropdown d-inline-block dd-backdrop dd-backdrop-none-md'>
    <a class='card-toolbar-btn text-dark' href='#' role='button' id='dropdownMenuLink4' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
        <i class='fa fa-list' aria-hidden="true"></i>
    </a>
    <div class='dropdown-menu dropdown-menu-right dropdown-caret dd-slide-center dd-slide-none-md dropdown-animated animated-2  brc-danger-tp2 border-t-3' aria-labelledby='dropdownMenuLink4'>
        <div class='dropdown-inner'>
            @if (Model.EditLink != null)
            {
                if (User.Identity.Roles().Contains("1") || User.Identity.Roles().Contains("3"))
                {
                    <a class='dropdown-item btn btn-outline-danger btn-h-light-danger btn-a-light-danger my-1 text-90 font-bolder text-uppercase'
                       href='@Model.EditLink/@Model.Id'>
                        <i class='fas fa-edit text-dark text-140 w-3 mr-2px' aria-hidden="true"></i>
                        Editar Datos...
                    </a>

                    <div class='dropdown-divider m-1'></div>
                }
            }
            @if (Model.DetailLink != null)
            {
                <a class='dropdown-item btn btn-outline-danger btn-h-light-danger btn-a-light-danger my-1 text-90 font-bolder text-uppercase'
                   href='@Model.DetailLink/@Model.Id'>
                    <i class='fas fa-search text-dark text-140 w-3 mr-2px' aria-hidden="true"></i>
                    Ver Detalle...
                </a>

                <div class="dropdown-divider m-1"></div>
            }
            @if (Model.CompleteLink != null)
            {
                if (User.Identity.Roles().Contains("1") || User.Identity.Roles().Contains("3"))
                {
                    <a class="dropdown-item btn btn-outline-danger btn-h-light-danger btn-a-light-danger my-1 text-90 font-bolder text-uppercase"
                       href='@Model.CompleteLink/@Model.Id'>
                        <i class='fas fa-clipboard-list text-dark text-140 w-3 mr-2px' aria-hidden="true"></i>
                        Completar datos...
                    </a>

                    <div class='dropdown-divider m-1'></div>
                }
            }
            @if (Model.Delete != null)
            {
                if (User.Identity.Roles().Contains("1"))
                {
                    <a href='javascript:ActivarUser("@Model.Id", "@Model.Delete")' class='dropdown-item btn btn-outline-danger btn-h-light-danger btn-a-light-danger my-1 text-90 font-bolder text-uppercase'>
                        <i class='fas fa-trash text-dark text-140 w-3 mr-2px' aria-hidden="true"></i>
                        Eliminar
                    </a>
                }
            }
            @if (Model.ModalDetail != null)
            {
                if (User.Identity.Roles().Contains("1"))
                {
                    <a href='javascript:ShowModal("@Model.Id")' class='dropdown-item btn btn-outline-danger btn-h-light-danger btn-a-light-danger my-1 text-90 font-bolder text-uppercase'>
                        <i class='fas fa-trash text-dark text-140 w-3 mr-2px' aria-hidden="true"></i>
                        Eliminar
                    </a>
                }
            }
        </div>
    </div>
</div>